// ─── EXAM DATA ────────────────────────────────────────────────────────────────
// 6 levels × 2 variants × 20 questions = 240 questions total
// Types: match (MC), pinyin (type answer), hanzi (select char), translate (pick sentence)

export const LEVEL_META = [
  {
    id: "intro",
    name: "Intro Level",
    hsk: "HSK 1",
    color: "#27ae60",
    icon: "🌱",
    description: "Greetings, pronouns, 是 sentences, basic numbers",
  },
  {
    id: "book1",
    name: "Book 1",
    hsk: "HSK 1–2",
    color: "#2c5f8a",
    icon: "📘",
    description: "Numbers, dates, time, family, colors, hobbies, pets",
  },
  {
    id: "book2",
    name: "Book 2",
    hsk: "HSK 2",
    color: "#8e44ad",
    icon: "📗",
    description: "Weather, school, food, house, neighborhood",
  },
  {
    id: "book3",
    name: "Book 3",
    hsk: "HSK 2–3",
    color: "#c0392b",
    icon: "📕",
    description: "Personality, health, festivals, directions, technology",
  },
  {
    id: "book4",
    name: "Book 4",
    hsk: "HSK 3",
    color: "#d4a017",
    icon: "📙",
    description: "Travel, culture, shopping, martial arts, social media",
  },
  {
    id: "book5",
    name: "Book 5",
    hsk: "HSK 3–4",
    color: "#1a7a5a",
    icon: "📒",
    description: "Healthcare, sports, music, architecture, environment",
  },
];

// ─── INTRO LEVEL ──────────────────────────────────────────────────────────────

const introA = [
  { type: "match", question: "What does 你好 mean?", options: ["Goodbye", "Hello", "Thank you", "Sorry"], answer: 1 },
  { type: "match", question: "What does 谢谢 mean?", options: ["Sorry", "Please", "Thank you", "Goodbye"], answer: 2 },
  { type: "pinyin", question: "Type the pinyin for: 你", answer: "nǐ" },
  { type: "hanzi", question: "Select the character for 'wǒ' (I / me)", options: ["他", "她", "我", "你"], answer: 2 },
  { type: "match", question: "What does 对不起 mean?", options: ["Thank you", "Sorry", "You're welcome", "Goodbye"], answer: 1 },
  { type: "match", question: "What does 再见 mean?", options: ["Hello", "Please", "Goodbye", "Sorry"], answer: 2 },
  { type: "pinyin", question: "Type the pinyin for: 我", answer: "wǒ" },
  { type: "hanzi", question: "Select the character for 'tā' (he)", options: ["你", "我", "她", "他"], answer: 3 },
  { type: "match", question: "What is the response to 谢谢?", options: ["再见", "你好", "没关系", "不客气"], answer: 3 },
  { type: "translate", question: "How do you say 'I am a student'?", options: ["你是老师", "我是学生", "他是朋友", "我不是"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 是", answer: "shì" },
  { type: "match", question: "What does 请 mean?", options: ["Sorry", "Please", "Thank you", "Excuse me"], answer: 1 },
  { type: "hanzi", question: "Select the hanzi for 'lǎoshī' (teacher)", options: ["老师", "学生", "朋友", "同学"], answer: 0 },
  { type: "match", question: "Which number is 五?", options: ["Three", "Four", "Five", "Six"], answer: 2 },
  { type: "pinyin", question: "Type the pinyin for: 三", answer: "sān" },
  { type: "match", question: "What does 没关系 mean?", options: ["Sorry", "Thank you", "It's okay", "Goodbye"], answer: 2 },
  { type: "hanzi", question: "Select the hanzi for 'nǐmen' (you plural)", options: ["我们", "你们", "他们", "她们"], answer: 1 },
  { type: "translate", question: "How do you say 'Hello, teacher!'?", options: ["谢谢老师！", "再见老师！", "老师好！", "老师，你好吗？"], answer: 2 },
  { type: "match", question: "What does 不 mean?", options: ["Yes", "Maybe", "Not / No", "Also"], answer: 2 },
  { type: "pinyin", question: "Type the pinyin for: 好", answer: "hǎo" },
];

const introB = [
  { type: "match", question: "What does 不客气 mean?", options: ["Sorry", "Thank you", "You're welcome", "Goodbye"], answer: 2 },
  { type: "hanzi", question: "Select the character for 'tā' (she)", options: ["他", "我", "你", "她"], answer: 3 },
  { type: "pinyin", question: "Type the pinyin for: 谢谢", answer: "xiè xie" },
  { type: "match", question: "What does 老师 mean?", options: ["Student", "Friend", "Teacher", "Family"], answer: 2 },
  { type: "translate", question: "How do you say 'She is not a teacher'?", options: ["她是老师", "她不是老师", "他不是学生", "你是老师"], answer: 1 },
  { type: "match", question: "Which number is 四?", options: ["Two", "Three", "Four", "Five"], answer: 2 },
  { type: "pinyin", question: "Type the pinyin for: 再见", answer: "zài jiàn" },
  { type: "hanzi", question: "Select the character for 'sān' (three)", options: ["一", "二", "三", "四"], answer: 2 },
  { type: "match", question: "What does 我们 mean?", options: ["I / me", "You", "We / us", "They"], answer: 2 },
  { type: "match", question: "What is the response to 对不起?", options: ["再见", "谢谢", "没关系", "不客气"], answer: 2 },
  { type: "pinyin", question: "Type the pinyin for: 请", answer: "qǐng" },
  { type: "match", question: "What does 学生 mean?", options: ["Teacher", "Student", "Friend", "Family"], answer: 1 },
  { type: "hanzi", question: "Select the character for 'wǔ' (five)", options: ["三", "四", "五", "六"], answer: 2 },
  { type: "match", question: "What does 名字 mean?", options: ["Age", "Name", "Job", "Address"], answer: 1 },
  { type: "translate", question: "How do you say 'What is your name?'", options: ["你好吗？", "你叫什么名字？", "你是谁？", "你从哪里来？"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 他", answer: "tā" },
  { type: "match", question: "What does 朋友 mean?", options: ["Teacher", "Family", "Friend", "Colleague"], answer: 2 },
  { type: "hanzi", question: "Select the character for 'nǐ' (you)", options: ["我", "他", "你", "她"], answer: 2 },
  { type: "match", question: "Which number is 十?", options: ["Eight", "Nine", "Ten", "Eleven"], answer: 2 },
  { type: "translate", question: "How do you say 'We are all students'?", options: ["我们都是老师", "你们是学生", "我们都是学生", "他们不是学生"], answer: 2 },
];

// ─── BOOK 1 LEVEL ─────────────────────────────────────────────────────────────

const book1A = [
  { type: "match", question: "What does 爸爸 mean?", options: ["Mother", "Father", "Brother", "Sister"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 星期一", answer: "xīng qī yī" },
  { type: "hanzi", question: "Select the character for 'hóng' (red)", options: ["黄", "红", "蓝", "绿"], answer: 1 },
  { type: "match", question: "What does 上午 mean?", options: ["Evening", "Afternoon", "Morning", "Night"], answer: 2 },
  { type: "translate", question: "How do you say 'Today is Monday'?", options: ["今天是星期二", "今天是星期一", "明天是星期一", "昨天是星期一"], answer: 1 },
  { type: "match", question: "What does 哥哥 mean?", options: ["Younger brother", "Older brother", "Older sister", "Younger sister"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 颜色", answer: "yán sè" },
  { type: "match", question: "What does 游泳 mean?", options: ["Running", "Swimming", "Cycling", "Dancing"], answer: 1 },
  { type: "hanzi", question: "Select the character for 'māo' (cat)", options: ["狗", "猫", "鱼", "鸟"], answer: 1 },
  { type: "match", question: "What time is 三点半?", options: ["2:30", "3:00", "3:30", "4:30"], answer: 2 },
  { type: "translate", question: "How do you say 'I wake up at 7 o'clock'?", options: ["我七点睡觉", "我七点起床", "我六点起床", "我七点吃饭"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 衣服", answer: "yī fu" },
  { type: "match", question: "What does 下午 mean?", options: ["Morning", "Afternoon", "Evening", "Midnight"], answer: 1 },
  { type: "hanzi", question: "Select the character for 'lǜ' (green)", options: ["黄", "红", "绿", "蓝"], answer: 2 },
  { type: "match", question: "What does 妹妹 mean?", options: ["Older sister", "Older brother", "Younger sister", "Younger brother"], answer: 2 },
  { type: "match", question: "Which day is 星期三?", options: ["Tuesday", "Wednesday", "Thursday", "Friday"], answer: 1 },
  { type: "translate", question: "How do you say 'My hobby is reading'?", options: ["我的爱好是看书", "我的爱好是游泳", "他的爱好是看书", "我没有爱好"], answer: 0 },
  { type: "pinyin", question: "Type the pinyin for: 狗", answer: "gǒu" },
  { type: "match", question: "What does 帽子 mean?", options: ["Shoes", "Shirt", "Hat", "Pants"], answer: 2 },
  { type: "hanzi", question: "Select the character for 'bái' (white)", options: ["黑", "白", "灰", "棕"], answer: 1 },
];

const book1B = [
  { type: "match", question: "What does 妈妈 mean?", options: ["Father", "Mother", "Grandmother", "Aunt"], answer: 1 },
  { type: "hanzi", question: "Select the character for 'gǒu' (dog)", options: ["猫", "狗", "鱼", "鸟"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 弟弟", answer: "dì di" },
  { type: "match", question: "What does 晚上 mean?", options: ["Morning", "Afternoon", "Evening / Night", "Midnight"], answer: 2 },
  { type: "translate", question: "How do you say 'My sister likes cats'?", options: ["我姐姐喜欢狗", "我妹妹喜欢猫", "我哥哥喜欢猫", "我妈妈喜欢猫"], answer: 1 },
  { type: "match", question: "What does 打球 mean?", options: ["Play piano", "Play ball", "Play chess", "Play games"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 睡觉", answer: "shuì jiào" },
  { type: "match", question: "Which color is 黄色?", options: ["Red", "Blue", "Green", "Yellow"], answer: 3 },
  { type: "hanzi", question: "Select the character for 'lán' (blue)", options: ["绿", "红", "蓝", "黄"], answer: 2 },
  { type: "match", question: "What does 裤子 mean?", options: ["Shirt", "Pants", "Shoes", "Hat"], answer: 1 },
  { type: "translate", question: "How do you say 'Today is Saturday'?", options: ["今天是星期六", "今天是星期五", "明天是星期六", "今天是星期天"], answer: 0 },
  { type: "pinyin", question: "Type the pinyin for: 鞋子", answer: "xié zi" },
  { type: "match", question: "What does 姐姐 mean?", options: ["Younger sister", "Younger brother", "Older sister", "Older brother"], answer: 2 },
  { type: "hanzi", question: "Select the character for 'hēi' (black)", options: ["白", "黑", "灰", "棕"], answer: 1 },
  { type: "match", question: "What time of day is 早上?", options: ["Afternoon", "Evening", "Morning", "Midnight"], answer: 2 },
  { type: "match", question: "What does 看电视 mean?", options: ["Read books", "Watch TV", "Listen to music", "Play games"], answer: 1 },
  { type: "translate", question: "How do you say 'He goes to bed at 10'?", options: ["他十点起床", "他十点睡觉", "他十点吃饭", "他十点学习"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 爸爸", answer: "bà ba" },
  { type: "match", question: "What does 爱好 mean?", options: ["Habit", "Hobby / Interest", "Work", "Study"], answer: 1 },
  { type: "hanzi", question: "Select the character for 'niǎo' (bird)", options: ["猫", "狗", "鱼", "鸟"], answer: 3 },
];

// ─── BOOK 2 LEVEL ─────────────────────────────────────────────────────────────

const book2A = [
  { type: "match", question: "What does 下雨 mean?", options: ["Sunny", "Snowing", "Raining", "Windy"], answer: 2 },
  { type: "pinyin", question: "Type the pinyin for: 苹果", answer: "píng guǒ" },
  { type: "hanzi", question: "Select the character for 'xuéxiào' (school)", options: ["医院", "学校", "银行", "超市"], answer: 1 },
  { type: "match", question: "What does 春天 mean?", options: ["Summer", "Autumn", "Winter", "Spring"], answer: 3 },
  { type: "translate", question: "How do you say 'I have a headache'?", options: ["我肚子疼", "我头疼", "我发烧了", "我感冒了"], answer: 1 },
  { type: "match", question: "What does 超市 mean?", options: ["Hospital", "Bank", "Supermarket", "School"], answer: 2 },
  { type: "pinyin", question: "Type the pinyin for: 天气", answer: "tiān qì" },
  { type: "match", question: "What does 作业 mean?", options: ["Exam", "Class", "Homework", "Teacher"], answer: 2 },
  { type: "hanzi", question: "Select the character for 'chúfáng' (kitchen)", options: ["客厅", "卧室", "厨房", "浴室"], answer: 2 },
  { type: "match", question: "What does 发烧 mean?", options: ["Headache", "Stomachache", "Cough", "Fever"], answer: 3 },
  { type: "translate", question: "How do you say 'It's snowing today'?", options: ["今天下雨", "今天刮风", "今天下雪", "今天晴天"], answer: 2 },
  { type: "pinyin", question: "Type the pinyin for: 西瓜", answer: "xī guā" },
  { type: "match", question: "What does 卧室 mean?", options: ["Living room", "Kitchen", "Bedroom", "Bathroom"], answer: 2 },
  { type: "hanzi", question: "Select the character for 'yīyuàn' (hospital)", options: ["学校", "银行", "医院", "超市"], answer: 2 },
  { type: "match", question: "What does 打电话 mean?", options: ["Send a message", "Make a phone call", "Browse the internet", "Watch a video"], answer: 1 },
  { type: "match", question: "Which season is 冬天?", options: ["Spring", "Summer", "Autumn", "Winter"], answer: 3 },
  { type: "translate", question: "How do you say 'I want to see a doctor'?", options: ["我要吃药", "我要看医生", "我要休息", "我要打针"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 香蕉", answer: "xiāng jiāo" },
  { type: "match", question: "What does 考试 mean?", options: ["Homework", "Class", "Exam / Test", "Study"], answer: 2 },
  { type: "hanzi", question: "Select the character for 'kètīng' (living room)", options: ["卧室", "厨房", "客厅", "浴室"], answer: 2 },
];

const book2B = [
  { type: "match", question: "What does 秋天 mean?", options: ["Spring", "Summer", "Autumn", "Winter"], answer: 2 },
  { type: "hanzi", question: "Select the character for 'shǒujī' (mobile phone)", options: ["电脑", "手机", "电视", "相机"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 白菜", answer: "bái cài" },
  { type: "match", question: "What does 晴天 mean?", options: ["Cloudy day", "Rainy day", "Sunny day", "Snowy day"], answer: 2 },
  { type: "translate", question: "How do you say 'My house has three bedrooms'?", options: ["我家有三个卫生间", "我家有三个卧室", "我家有两个厨房", "我家有三个客厅"], answer: 1 },
  { type: "match", question: "What does 爷爷 mean?", options: ["Grandmother (paternal)", "Grandfather (maternal)", "Grandfather (paternal)", "Uncle"], answer: 2 },
  { type: "pinyin", question: "Type the pinyin for: 西红柿", answer: "xī hóng shì" },
  { type: "match", question: "What does 短信 mean?", options: ["Phone call", "Email", "Text message", "Letter"], answer: 2 },
  { type: "hanzi", question: "Select the character for 'yínháng' (bank)", options: ["超市", "医院", "学校", "银行"], answer: 3 },
  { type: "match", question: "What does 吃药 mean?", options: ["See a doctor", "Take medicine", "Have a fever", "Rest"], answer: 1 },
  { type: "translate", question: "How do you say 'The weather today is very cold'?", options: ["今天天气很热", "今天天气很冷", "今天天气很好", "今天刮风了"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 浴室", answer: "yù shì" },
  { type: "match", question: "What does 奶奶 mean?", options: ["Paternal grandfather", "Paternal grandmother", "Maternal grandmother", "Aunt"], answer: 1 },
  { type: "hanzi", question: "Select the character for 'xià xuě' (snowing)", options: ["下雨", "刮风", "下雪", "晴天"], answer: 2 },
  { type: "match", question: "What does 上课 mean?", options: ["Finish class", "Start / attend class", "Skip class", "Study at home"], answer: 1 },
  { type: "match", question: "What does 夏天 mean?", options: ["Spring", "Summer", "Autumn", "Winter"], answer: 1 },
  { type: "translate", question: "How do you say 'I want to order food'?", options: ["我想结账", "我想点菜", "我想看菜单", "我想喝水"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 早饭", answer: "zǎo fàn" },
  { type: "match", question: "What does 下课 mean?", options: ["Start class", "Skip class", "Finish class", "Study"], answer: 2 },
  { type: "hanzi", question: "Select the character for 'fùjìn' (nearby)", options: ["远处", "附近", "中间", "对面"], answer: 1 },
];

// ─── BOOK 3 LEVEL ─────────────────────────────────────────────────────────────

const book3A = [
  { type: "match", question: "What does 聪明 mean?", options: ["Lazy", "Smart / Clever", "Shy", "Hardworking"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 春节", answer: "chūn jié" },
  { type: "hanzi", question: "Select the character for 'zuǒ' (left)", options: ["右", "左", "直", "前"], answer: 1 },
  { type: "match", question: "What does 锻炼 mean?", options: ["Rest", "Exercise / Work out", "Diet", "Sleep"], answer: 1 },
  { type: "translate", question: "How do you say 'Turn left at the traffic light'?", options: ["到红绿灯右转", "到红绿灯直走", "到红绿灯左转", "到红绿灯停下"], answer: 2 },
  { type: "match", question: "What does 环境 mean?", options: ["Technology", "Culture", "Environment", "Society"], answer: 2 },
  { type: "pinyin", question: "Type the pinyin for: 健康", answer: "jiàn kāng" },
  { type: "match", question: "What does 开朗 mean?", options: ["Shy", "Quiet", "Outgoing / Cheerful", "Serious"], answer: 2 },
  { type: "hanzi", question: "Select the character for 'wǎngluò' (internet)", options: ["电脑", "手机", "网络", "软件"], answer: 2 },
  { type: "match", question: "What does 中秋节 mean?", options: ["Spring Festival", "Lantern Festival", "Dragon Boat Festival", "Mid-Autumn Festival"], answer: 3 },
  { type: "translate", question: "How do you say 'The environment here is very beautiful'?", options: ["这里的天气很好", "这里的环境很美", "这里的人很友好", "这里的食物很好吃"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 污染", answer: "wū rǎn" },
  { type: "match", question: "What does 勤劳 mean?", options: ["Lazy", "Smart", "Hardworking / Diligent", "Kind"], answer: 2 },
  { type: "hanzi", question: "Select the character for 'yòu' (right)", options: ["左", "右", "前", "后"], answer: 1 },
  { type: "match", question: "What does 减肥 mean?", options: ["Gain weight", "Lose weight / Diet", "Exercise", "Eat healthily"], answer: 1 },
  { type: "match", question: "What does 元宵节 mean?", options: ["Mid-Autumn Festival", "Spring Festival", "Lantern Festival", "Dragon Boat Festival"], answer: 2 },
  { type: "translate", question: "How do you say 'He is a very outgoing person'?", options: ["他是一个很害羞的人", "他是一个很勤劳的人", "他是一个很开朗的人", "他是一个很聪明的人"], answer: 2 },
  { type: "pinyin", question: "Type the pinyin for: 方向", answer: "fāng xiàng" },
  { type: "match", question: "What does 害羞 mean?", options: ["Brave", "Outgoing", "Shy", "Confident"], answer: 2 },
  { type: "hanzi", question: "Select the character for 'bǎohù' (protect)", options: ["破坏", "保护", "污染", "改变"], answer: 1 },
];

const book3B = [
  { type: "match", question: "What does 直走 mean?", options: ["Turn left", "Turn right", "Go straight", "Stop"], answer: 2 },
  { type: "hanzi", question: "Select the character for 'chūnjié' (Spring Festival)", options: ["中秋节", "元宵节", "春节", "端午节"], answer: 2 },
  { type: "pinyin", question: "Type the pinyin for: 营养", answer: "yíng yǎng" },
  { type: "match", question: "What does 社会 mean?", options: ["Technology", "Society", "Culture", "Nature"], answer: 1 },
  { type: "translate", question: "How do you say 'I need to exercise more'?", options: ["我需要多休息", "我需要多吃饭", "我需要多锻炼", "我需要多睡觉"], answer: 2 },
  { type: "match", question: "What does 素食 mean?", options: ["Meat diet", "Seafood diet", "Vegetarian diet", "Fast food"], answer: 2 },
  { type: "pinyin", question: "Type the pinyin for: 智能手机", answer: "zhì néng shǒu jī" },
  { type: "match", question: "What does 地铁 mean?", options: ["Bus", "Taxi", "Train", "Subway / Metro"], answer: 3 },
  { type: "hanzi", question: "Select the character for 'kāilǎng' (outgoing)", options: ["害羞", "勤劳", "开朗", "聪明"], answer: 2 },
  { type: "match", question: "What does 端午节 mean?", options: ["Mid-Autumn Festival", "Lantern Festival", "Dragon Boat Festival", "Spring Festival"], answer: 2 },
  { type: "translate", question: "How do you say 'Please don't pollute the environment'?", options: ["请不要破坏环境", "请不要污染环境", "请保护自然", "请爱护环境"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 个性", answer: "gè xìng" },
  { type: "match", question: "What does 前面 mean?", options: ["Behind", "Beside", "In front", "Above"], answer: 2 },
  { type: "hanzi", question: "Select the character for 'jiànkāng' (healthy)", options: ["生病", "健康", "锻炼", "休息"], answer: 1 },
  { type: "match", question: "What does 后面 mean?", options: ["In front", "Beside", "Above", "Behind"], answer: 3 },
  { type: "match", question: "What does 饮食习惯 mean?", options: ["Exercise habits", "Study habits", "Eating habits", "Sleep habits"], answer: 2 },
  { type: "translate", question: "How do you say 'Spring Festival is the most important festival in China'?", options: ["中秋节是中国最重要的节日", "春节是中国最重要的节日", "端午节是中国最重要的节日", "元宵节是中国最重要的节日"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 附近", answer: "fù jìn" },
  { type: "match", question: "What does 自然 mean?", options: ["Society", "Technology", "Culture", "Nature"], answer: 3 },
  { type: "hanzi", question: "Select the character for 'jìshù' (technology)", options: ["文化", "社会", "技术", "环境"], answer: 2 },
];

// ─── BOOK 4 LEVEL ─────────────────────────────────────────────────────────────

const book4A = [
  { type: "match", question: "What does 护照 mean?", options: ["Visa", "Passport", "Ticket", "ID card"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 太极拳", answer: "tài jí quán" },
  { type: "hanzi", question: "Select the character for 'shāngdiàn' (shop/store)", options: ["超市", "商店", "餐厅", "银行"], answer: 1 },
  { type: "match", question: "What does 打折 mean?", options: ["Full price", "Discount", "Free", "Expensive"], answer: 1 },
  { type: "translate", question: "How do you say 'I want to book a flight ticket'?", options: ["我想预订火车票", "我想预订机票", "我想预订酒店", "我想取消预订"], answer: 1 },
  { type: "match", question: "What does 微信 mean?", options: ["Weibo", "WeChat", "TikTok", "Email"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 电子邮件", answer: "diàn zǐ yóu jiàn" },
  { type: "match", question: "What does 武术 mean?", options: ["Tai Chi", "Martial arts", "Kung Fu specifically", "Dance"], answer: 1 },
  { type: "hanzi", question: "Select the character for 'qiānzhèng' (visa)", options: ["护照", "签证", "机票", "身份证"], answer: 1 },
  { type: "match", question: "What does 预习 mean?", options: ["Review after class", "Preview before class", "Skip class", "Study during class"], answer: 1 },
  { type: "translate", question: "How do you say 'This item is on sale, 20% off'?", options: ["这件商品打八折", "这件商品打七折", "这件商品打九折", "这件商品打五折"], answer: 0 },
  { type: "pinyin", question: "Type the pinyin for: 文化", answer: "wén huà" },
  { type: "match", question: "What does 复习 mean?", options: ["Preview lesson", "Review / revise", "Skip class", "Take notes"], answer: 1 },
  { type: "hanzi", question: "Select the character for 'jīchǎng' (airport)", options: ["火车站", "机场", "码头", "汽车站"], answer: 1 },
  { type: "match", question: "What does 朋友圈 mean?", options: ["Friend group", "WeChat Moments", "Social circle", "Online community"], answer: 1 },
  { type: "match", question: "What does 传统 mean?", options: ["Modern", "Technology", "Tradition", "Culture"], answer: 2 },
  { type: "translate", question: "How do you say 'I need to write an email to my teacher'?", options: ["我需要给老师打电话", "我需要给老师发短信", "我需要给老师写电子邮件", "我需要见老师"], answer: 2 },
  { type: "pinyin", question: "Type the pinyin for: 功夫", answer: "gōng fu" },
  { type: "match", question: "What does 图书馆 mean?", options: ["Bookshop", "Library", "Museum", "Study room"], answer: 1 },
  { type: "hanzi", question: "Select the character for 'wēibó' (Weibo)", options: ["微信", "微博", "抖音", "邮件"], answer: 1 },
];

const book4B = [
  { type: "match", question: "What does 旅游 mean?", options: ["Business trip", "Travel / Tourism", "Study abroad", "Move house"], answer: 1 },
  { type: "hanzi", question: "Select the character for 'túshūguǎn' (library)", options: ["博物馆", "图书馆", "美术馆", "体育馆"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 世界公民", answer: "shì jiè gōng mín" },
  { type: "match", question: "What does 特价 mean?", options: ["Regular price", "Special/sale price", "Expensive", "Free"], answer: 1 },
  { type: "translate", question: "How do you say 'He practices Tai Chi every morning'?", options: ["他每天早上练功夫", "他每天早上练太极拳", "他每天早上练武术", "他每天早上跑步"], answer: 1 },
  { type: "match", question: "What does 软件 mean?", options: ["Hardware", "Software", "Application", "Program"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 签证", answer: "qiān zhèng" },
  { type: "match", question: "What does 酒店 mean?", options: ["Restaurant", "Bar", "Hotel", "Café"], answer: 2 },
  { type: "hanzi", question: "Select the character for 'fùxí' (review/revise)", options: ["预习", "复习", "学习", "练习"], answer: 1 },
  { type: "match", question: "What does 社交媒体 mean?", options: ["Traditional media", "Social media", "News media", "Broadcast media"], answer: 1 },
  { type: "translate", question: "How do you say 'Chinese martial arts culture is very profound'?", options: ["中国武术文化很有趣", "中国武术文化很深厚", "中国传统文化很有名", "中国功夫电影很好看"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 习惯", answer: "xí guàn" },
  { type: "match", question: "What does 风俗 mean?", options: ["Technology", "Tradition", "Custom / Folk practice", "Culture"], answer: 2 },
  { type: "hanzi", question: "Select the character for 'bìngdú' (computer virus)", options: ["软件", "硬件", "病毒", "程序"], answer: 2 },
  { type: "match", question: "What does 购物 mean?", options: ["Go to work", "Go shopping", "Go to school", "Go travelling"], answer: 1 },
  { type: "match", question: "What does 笔记本 mean?", options: ["Pen", "Notebook (book)", "Laptop", "Notebook or Laptop (context)"], answer: 3 },
  { type: "translate", question: "How do you say 'I prefer to shop online'?", options: ["我更喜欢去商场购物", "我更喜欢网上购物", "我更喜欢去超市购物", "我不喜欢购物"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 附件", answer: "fù jiàn" },
  { type: "match", question: "What does 世界公民 mean?", options: ["World traveller", "Global citizen", "International student", "Foreign visitor"], answer: 1 },
  { type: "hanzi", question: "Select the character for 'jīpiào' (plane ticket)", options: ["火车票", "机票", "船票", "汽车票"], answer: 1 },
];

// ─── BOOK 5 LEVEL ─────────────────────────────────────────────────────────────

const book5A = [
  { type: "match", question: "What does 志愿者 mean?", options: ["Athlete", "Volunteer", "Scientist", "Artist"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 建筑", answer: "jiàn zhù" },
  { type: "hanzi", question: "Select the character for 'yīliáo' (healthcare/medical)", options: ["教育", "医疗", "科技", "艺术"], answer: 1 },
  { type: "match", question: "What does 可持续发展 mean?", options: ["Economic development", "Rapid development", "Sustainable development", "Cultural development"], answer: 2 },
  { type: "translate", question: "How do you say 'She is a world-famous architect'?", options: ["她是世界著名的医生", "她是世界著名的科学家", "她是世界著名的建筑师", "她是世界著名的运动员"], answer: 2 },
  { type: "match", question: "What does 运动员 mean?", options: ["Coach", "Referee", "Athlete / Sportsperson", "Spectator"], answer: 2 },
  { type: "pinyin", question: "Type the pinyin for: 科学家", answer: "kē xué jiā" },
  { type: "match", question: "What does 绿色出行 mean?", options: ["Drive by car", "Travel by plane", "Eco-friendly transport", "Travel abroad"], answer: 2 },
  { type: "hanzi", question: "Select the character for 'yuányīn' (reason/cause)", options: ["结果", "原因", "目的", "方法"], answer: 1 },
  { type: "match", question: "What does 古典音乐 mean?", options: ["Rock music", "Pop music", "Folk music", "Classical music"], answer: 3 },
  { type: "translate", question: "How do you say 'We should protect the environment together'?", options: ["我们应该一起学习", "我们应该一起保护环境", "我们应该一起锻炼身体", "我们应该一起节约用水"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 节约", answer: "jié yuē" },
  { type: "match", question: "What does 生活方式 mean?", options: ["Work style", "Communication style", "Lifestyle", "Learning style"], answer: 2 },
  { type: "hanzi", question: "Select the character for 'jiāotōng' (transportation)", options: ["环境", "交通", "经济", "教育"], answer: 1 },
  { type: "match", question: "What does 碳排放 mean?", options: ["Air pollution", "Carbon emissions", "Water pollution", "Noise pollution"], answer: 1 },
  { type: "match", question: "What does 文化遗产 mean?", options: ["Cultural exchange", "Cultural heritage", "Cultural innovation", "Cultural education"], answer: 1 },
  { type: "translate", question: "How do you say 'Exercise is very important for health'?", options: ["睡眠对健康很重要", "运动对健康很重要", "饮食对健康很重要", "工作对健康很重要"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 环保", answer: "huán bǎo" },
  { type: "match", question: "What does 医疗保险 mean?", options: ["Life insurance", "Car insurance", "Health insurance", "Property insurance"], answer: 2 },
  { type: "hanzi", question: "Select the character for 'zhìyuànzhě' (volunteer)", options: ["运动员", "科学家", "志愿者", "艺术家"], answer: 2 },
];

const book5B = [
  { type: "match", question: "What does 可再生能源 mean?", options: ["Nuclear energy", "Fossil fuels", "Renewable energy", "Solar energy only"], answer: 2 },
  { type: "hanzi", question: "Select the character for 'jiànzhúshī' (architect)", options: ["工程师", "建筑师", "设计师", "艺术家"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 音乐家", answer: "yīn yuè jiā" },
  { type: "match", question: "What does 医疗系统 mean?", options: ["Education system", "Medical / Healthcare system", "Legal system", "Transport system"], answer: 1 },
  { type: "translate", question: "How do you say 'This building won an international architecture award'?", options: ["这栋建筑获得了国际设计奖", "这栋建筑获得了国际建筑奖", "这栋建筑是世界最高的", "这栋建筑非常有名"], answer: 1 },
  { type: "match", question: "What does 改变生活习惯 mean?", options: ["Improve study habits", "Change lifestyle habits", "Maintain healthy habits", "Develop new skills"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 贡献", answer: "gòng xiàn" },
  { type: "match", question: "What does 民族音乐 mean?", options: ["Classical music", "Western music", "Rock music", "Ethnic/Folk music"], answer: 3 },
  { type: "hanzi", question: "Select the character for 'pǐnzhì' (quality)", options: ["数量", "品质", "价格", "特点"], answer: 1 },
  { type: "match", question: "What does 体育精神 mean?", options: ["Sports skills", "Sportsmanship / Sports spirit", "Competitive spirit", "Team spirit"], answer: 1 },
  { type: "translate", question: "How do you say 'She made great contributions to medical science'?", options: ["她在体育方面做出了巨大贡献", "她在医学方面做出了巨大贡献", "她在建筑方面做出了巨大贡献", "她在音乐方面做出了巨大贡献"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 传承", answer: "chuán chéng" },
  { type: "match", question: "What does 低碳生活 mean?", options: ["High-carbon lifestyle", "Traditional lifestyle", "Low-carbon lifestyle", "Simple lifestyle"], answer: 2 },
  { type: "hanzi", question: "Select the character for 'pǔtōng huà' (Mandarin Chinese)", options: ["粤语", "闽南语", "普通话", "广东话"], answer: 2 },
  { type: "match", question: "What does 国际合作 mean?", options: ["National cooperation", "International cooperation", "Cultural exchange", "Economic trade"], answer: 1 },
  { type: "match", question: "What does 成语 mean?", options: ["Proverb", "Poem", "Idiom (4-character phrase)", "Folk saying"], answer: 2 },
  { type: "translate", question: "How do you say 'We need to reduce carbon emissions to protect the Earth'?", options: ["我们需要种更多树来保护地球", "我们需要减少碳排放来保护地球", "我们需要节约用水来保护地球", "我们需要减少污染来保护地球"], answer: 1 },
  { type: "pinyin", question: "Type the pinyin for: 文化遗产", answer: "wén huà yí chǎn" },
  { type: "match", question: "What does 心理健康 mean?", options: ["Physical health", "Mental health", "Social health", "Emotional intelligence"], answer: 1 },
  { type: "hanzi", question: "Select the character for 'shídài' (era/times)", options: ["历史", "时代", "未来", "过去"], answer: 1 },
];

// ─── EXPORT ───────────────────────────────────────────────────────────────────

export const EXAMS = {
  intro:  { a: introA,  b: introB  },
  book1:  { a: book1A,  b: book1B  },
  book2:  { a: book2A,  b: book2B  },
  book3:  { a: book3A,  b: book3B  },
  book4:  { a: book4A,  b: book4B  },
  book5:  { a: book5A,  b: book5B  },
};
